name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./website

      - name: Build and export static site
        run: npm run build
        working-directory: ./website

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CSC325_NEXT_SITE }}
          channelId: live
          projectId: csc325-next-site
          entryPoint: ./website
